from setuptools import setup

setup(
    name="noctua",
    version="1.0.0",
    description="Tool-CyberSec-Forensic-Noctua - Reverse Engineering Framework en Python",
    author="MethodWhite",
    author_email="methodwhite@proton.me",
    url="https://github.com/MethodWhite/Noctua",
    packages=["noctua"],
    package_dir={"noctua": "."},
    package_data={"noctua": [
        "core/*.py",
        "loaders/*.py",
        "modules/*.py",
        "analyzer/*.py",
        "attacks/*.py",
    ]},
    install_requires=[
        "capstone>=5.0",
        "numpy>=1.24",
        "scipy>=1.10",
        "pycryptodome>=3.18",
    ],
    python_requires=">=3.9",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Environment :: Console",
        "Intended Audience :: Developers",
        "Intended Audience :: Information Technology",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Security",
        "Topic :: Software Development :: Disassemblers",
    ],
)
