#!/usr/bin/env python3
"""
Noctua-c Frida Script Generator & Runtime Tracer

Generates Frida JavaScript hooks for FMOD audio runtime analysis,
connects to a target process, and dumps captured keys/data.

Usage:
    python3 noctua_frida.py generate        - Print Frida JS script to stdout
    python3 noctua_frida.py attach <name>   - Attach and trace process by name
    python3 noctua_frida.py android <pkg>   - Connect to Android device via ADB + Frida
"""

import argparse
import json
import os
import socket
import struct
import subprocess
import sys
import tempfile
import threading
import time
from pathlib import Path


FRIDA_SCRIPT_TEMPLATE = r"""
'use strict';

/* ============================================================
 * Noctua-c Frida Runtime Tracer
 * Generated by noctua_frida.py
 * ============================================================ */

/* --- Configuration --- */
const CONFIG = {
    logToConsole: true,
    dumpDir: '/data/local/tmp/noctua_dumps',
    keyOutputFile: '/data/local/tmp/noctua_key.txt',
    traceFmod: true,
    traceMemory: true,
    maxDumpSize: 1048576,  /* 1 MB per dump */
    processName: '%(process_name)s',
};

/* --- Globals --- */
let g_capturedKeys = [];
let g_capturedBanks = [];
let g_fmodSystemPtr = null;

/* --- Utility --- */
function hexify(arr) {
    return Array.prototype.map.call(new Uint8Array(arr), b =>
        ('0' + b.toString(16)).slice(-2)
    ).join('');
}

function strToBytes(s) {
    const buf = [];
    for (let i = 0; i < s.length; i++) {
        buf.push(s.charCodeAt(i) & 0xff);
    }
    return buf;
}

function writeToFile(path, data) {
    try {
        const f = new File(path, 'w+');
        f.write(data);
        f.flush();
        f.close();
        console.log('[Noctua] Wrote ' + data.length + ' bytes to ' + path);
    } catch (e) {
        console.log('[Noctua] Failed to write ' + path + ': ' + e);
    }
}

function appendToFile(path, data) {
    try {
        const f = new File(path, 'a+');
        f.write(data);
        f.flush();
        f.close();
    } catch (e) {
        console.log('[Noctua] Failed to append: ' + e);
    }
}

/* --- FMOD Hooks --- */

/* Hook 1: FMOD::System::setEncryptionKey(key, keylen) */
if (CONFIG.traceFmod) {
    const setEncKeyPtr = Module.findExportByName(null, '_ZN4FMOD6System16setEncryptionKeyEPKhi');
    if (setEncKeyPtr) {
        Interceptor.attach(setEncKeyPtr, {
            onEnter: function(args) {
                const keyPtr = args[1];
                const keyLen = args[2].toInt32();
                console.log('[Noctua] FMOD::System::setEncryptionKey called');
                console.log('[Noctua]   key ptr: ' + keyPtr);
                console.log('[Noctua]   key len: ' + keyLen);

                if (keyLen > 0 && keyPtr) {
                    const keyBytes = Memory.readByteArray(keyPtr, Math.min(keyLen, 64));
                    const keyHex = hexify(keyBytes);
                    console.log('[Noctua]   KEY DATA: ' + keyHex);
                    g_capturedKeys.push({
                        source: 'setEncryptionKey',
                        key: keyHex,
                        timestamp: Date.now()
                    });

                    const entry = JSON.stringify({
                        source: 'setEncryptionKey',
                        key: keyHex,
                        keyLen: keyLen,
                        ts: Date.now()
                    }) + '\n';
                    appendToFile(CONFIG.keyOutputFile, entry);

                    /* Also try to read the FMOD::System object pointer */
                    g_fmodSystemPtr = args[0];
                }
            }
        });
        console.log('[Noctua] Hooked FMOD::System::setEncryptionKey');
    } else {
        console.log('[Noctua] WARN: setEncryptionKey export not found, trying symbol search...');
        /* Search in loaded modules */
        const modules = Process.enumerateModules();
        for (const mod of modules) {
            const sym = Module.findExportByName(mod.name, '_ZN4FMOD6System16setEncryptionKeyEPKhi');
            if (sym) {
                console.log('[Noctua] Found setEncryptionKey in ' + mod.name);
                Interceptor.attach(sym, {
                    onEnter: function(args) {
                        const keyPtr = args[1];
                        const keyLen = args[2].toInt32();
                        if (keyLen > 0 && keyPtr) {
                            const keyBytes = Memory.readByteArray(keyPtr, Math.min(keyLen, 64));
                            const keyHex = hexify(keyBytes);
                            console.log('[Noctua]   KEY: ' + keyHex);
                            g_capturedKeys.push({source: 'setEncryptionKey', key: keyHex});
                            appendToFile(CONFIG.keyOutputFile,
                                JSON.stringify({source: 'setEncryptionKey', key: keyHex}) + '\n');
                        }
                    }
                });
                break;
            }
        }
    }

    /* Hook 2: FMOD::System::createSound */
    const createSoundPtr = Module.findExportByName(null, '_ZN4FMOD6System11createSoundEPKcjP17FMOD_CREATESOUNDEXPP21FMOD_CHANNELCONTROL');
    const createSoundAlt = Module.findExportByName(null, '_ZN4FMOD6System11createSoundEPKcjP17FMOD_CREATESOUNDEXPP10FMOD_SOUND');
    for (const ptr of [createSoundPtr, createSoundAlt]) {
        if (ptr) {
            Interceptor.attach(ptr, {
                onEnter: function(args) {
                    const namePtr = args[1];
                    let name = '(null)';
                    if (namePtr) {
                        try {
                            name = Memory.readUtf8String(namePtr) || '(empty)';
                        } catch (e) {
                            name = '(read error)';
                        }
                    }
                    console.log('[Noctua] FMOD::System::createSound: ' + name);
                    this.soundName = name;
                }
            });
            console.log('[Noctua] Hooked FMOD::System::createSound');
            break;
        }
    }

    /* Hook 3: FMOD::Studio::Bank::loadBank (via pattern or name) */
    const loadBankNames = [
        '_ZN4FMOD5Studio4Bank8loadBankEPKciP21FMOD_STUDIO_LOAD_BANK',
        '_ZN4FMOD5Studio4Bank8loadBankEPKc16FMOD_STUDIO_LOADINGBANK',
    ];
    for (const bn of loadBankNames) {
        const ptr = Module.findExportByName(null, bn);
        if (ptr) {
            Interceptor.attach(ptr, {
                onEnter: function(args) {
                    const bankPath = args[1] ? Memory.readUtf8String(args[1]) : '(null)';
                    console.log('[Noctua] FMOD::Studio::Bank::loadBank: ' + bankPath);
                    g_capturedBanks.push({path: bankPath, timestamp: Date.now()});
                }
            });
            console.log('[Noctua] Hooked FMOD::Studio::Bank::loadBank');
        }
    }
}

/* --- Memory Hooks --- */

/* Hook 4: Generic memory read tracer for key material */
/* Intercept memcpy to capture data copying near FMOD contexts */
if (CONFIG.traceMemory) {
    const memcpyPtr = Module.findExportByName(null, 'memcpy');
    if (memcpyPtr) {
        Interceptor.attach(memcpyPtr, {
            onEnter: function(args) {
                const dest = args[0];
                const src = args[1];
                const n = args[2].toInt32();

                /* Only trace transfers >= 16 bytes (potential key copy) */
                if (n < 16 || n > 256) return;

                /* Check if this is within FMOD heap region */
                const bt = Thread.backtrace(this.context, Backtracer.ACCURATE);
                const hasFmod = bt.some(a => {
                    const mod = Process.findModuleByAddress(a);
                    return mod && (mod.name.toLowerCase().indexOf('fmod') >= 0 ||
                                   mod.name.toLowerCase().indexOf('libil2cpp') >= 0);
                });

                if (hasFmod || (g_fmodSystemPtr && (
                    Math.abs(dest.toInt32() - g_fmodSystemPtr.toInt32()) < 0x100000 ||
                    Math.abs(src.toInt32() - g_fmodSystemPtr.toInt32()) < 0x100000
                ))) {
                    const data = Memory.readByteArray(src, n);
                    const hex = hexify(data);
                    console.log('[Noctua] memcpy(n=' + n + ') src=' + src + ' dst=' + dest);
                    console.log('[Noctua]   data: ' + hex);

                    if (n === 16) {
                        g_capturedKeys.push({source: 'memcpy_16', key: hex});
                        appendToFile(CONFIG.keyOutputFile,
                            JSON.stringify({source: 'memcpy_16', key: hex}) + '\n');
                    }
                }
            }
        });
        console.log('[Noctua] Hooked memcpy for key tracing');
    }

    /* Hook malloc/calloc to track FMOD heap allocations */
    const mallocPtr = Module.findExportByName(null, 'malloc');
    if (mallocPtr) {
        Interceptor.attach(mallocPtr, {
            onEnter: function(args) {
                this.size = args[0].toInt32();
            },
            onLeave: function(retval) {
                if (this.size === 16) {
                    console.log('[Noctua] malloc(16) -> ' + retval);
                }
            }
        });
    }
}

/* --- Dump on process resume --- */
console.log('[Noctua] Noctua-c Frida agent loaded on ' + CONFIG.processName);
console.log('[Noctua] Key output: ' + CONFIG.keyOutputFile);

/* Watch for keys periodically */
setInterval(function() {
    if (g_capturedKeys.length > 0) {
        const report = {
            timestamp: Date.now(),
            processName: CONFIG.processName,
            keys: g_capturedKeys,
            banks: g_capturedBanks,
            fmodPtr: g_fmodSystemPtr ? g_fmodSystemPtr.toString() : null
        };
        appendToFile(CONFIG.keyOutputFile, JSON.stringify(report) + '\n');
        console.log('[Noctua] Report: ' + g_capturedKeys.length + ' keys, ' +
                    g_capturedBanks.length + ' banks');
    }
}, 5000);

/* --- Cleanup handler --- */
Process.setExceptionHandler(function(details) {
    console.log('[Noctua] Exception: ' + JSON.stringify(details));
    return false;
});
"""


def generate_script(process_name="com.stellarforge.game"):
    """Generate the Frida JavaScript hook script."""
    return FRIDA_SCRIPT_TEMPLATE % {"process_name": process_name}


def attach_local(process_name):
    """Attach to a local process by name using Frida."""
    try:
        import frida
    except ImportError:
        print("[Noctua] frida module not installed. Try: pip install frida-tools")
        print("[Noctua] Falling back to script generation only.")
        script = generate_script(process_name)
        outpath = f"frida_noctua_{process_name}.js"
        with open(outpath, "w") as f:
            f.write(script)
        print(f"[Noctua] Script saved to {outpath}")
        print("[Noctua] Run manually: frida -n '{process_name}' -l {outpath}")
        return

    print(f"[Noctua] Attaching to process '{process_name}'...")
    try:
        session = frida.attach(process_name)
    except Exception as e:
        print(f"[Noctua] Could not attach: {e}")
        print("[Noctua] Is the process running? Try: frida-ps -U")
        return

    script_code = generate_script(process_name)
    script = session.create_script(script_code)
    script.load()
    print(f"[Noctua] Attached. Listening for FMOD calls...")

    key_file = f"noctua_keys_{process_name}.json"
    print(f"[Noctua] Keys will be saved to {key_file}")

    def on_message(message, data):
        if message["type"] == "send":
            print(f"[Frida] {message['payload']}")
        elif message["type"] == "error":
            print(f"[Frida Error] {message}")

    script.on("message", on_message)

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\n[Noctua] Detaching...")
        session.detach()


def attach_android(package_name):
    """Connect to Android device via ADB + Frida."""
    try:
        import frida
    except ImportError:
        print("[Noctua] frida module not installed.")
        return

    print(f"[Noctua] Connecting to Android device, attaching to {package_name}...")
    try:
        device = frida.get_usb_device()
        print(f"[Noctua] Device: {device}")
    except Exception as e:
        print(f"[Noctua] No USB device found: {e}")
        print("[Noctua] Make sure ADB is running and device is connected.")
        return

    try:
        session = device.attach(package_name)
    except Exception as e:
        print(f"[Noctua] Could not attach to {package_name}: {e}")
        print("[Noctua] Try spawning:")
        print(f"  frida -U -f {package_name} -l noctua_frida_script.js")
        return

    script_code = generate_script(package_name)
    script = session.create_script(script_code)
    script.load()
    print(f"[Noctua] Attached to {package_name} on Android.")

    key_file = f"noctua_keys_{package_name}.json"
    print(f"[Noctua] Keys will be saved to {key_file}")

    captured_keys = []

    def on_message(message, data):
        if message["type"] == "send":
            print(f"[Frida] {message['payload']}")
            try:
                payload = message["payload"]
                if "KEY" in payload and ":" in payload:
                    parts = payload.split("KEY: ")
                    if len(parts) > 1:
                        key_hex = parts[1].strip()
                        captured_keys.append(key_hex)
                        with open(key_file, "a") as f:
                            f.write(json.dumps({
                                "key": key_hex,
                                "source": payload,
                                "ts": time.time()
                            }) + "\n")
            except Exception:
                pass
        elif message["type"] == "error":
            print(f"[Frida Error] {message}")

    script.on("message", on_message)

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\n[Noctua] Detaching...")
        if captured_keys:
            print(f"[Noctua] Captured {len(captured_keys)} key(s):")
            for k in captured_keys:
                print(f"  {k}")
        with open(key_file, "w") as f:
            json.dump(captured_keys, f, indent=2)
        print(f"[Noctua] Keys saved to {key_file}")
        session.detach()


def dump_so_from_device(package_name, lib_name="libil2cpp.so"):
    """Pull a shared library from an Android device for analysis."""
    print(f"[Noctua] Attempting to pull {lib_name} from {package_name}...")
    try:
        # Find PID
        result = subprocess.run(
            ["adb", "shell", "pidof", package_name],
            capture_output=True, text=True, timeout=10
        )
        pid = result.stdout.strip()
        if not pid:
            print(f"[Noctua] {package_name} not running")
            return None

        # Find library path in /proc/pid/maps
        result = subprocess.run(
            ["adb", "shell", f"grep {lib_name} /proc/{pid}/maps"],
            capture_output=True, text=True, timeout=10
        )
        lines = result.stdout.strip().split("\n")
        if not lines or lines[0] == "":
            print(f"[Noctua] {lib_name} not found in process maps")
            return None

        # Parse first mapping to get path
        parts = lines[0].split()
        if len(parts) >= 6:
            lib_path = parts[-1]
        else:
            lib_path = f"/proc/{pid}/root/data/app/{package_name}/lib/arm64/{lib_name}"

        # Pull file
        out_path = f"{lib_name}.{pid}"
        subprocess.run(["adb", "pull", lib_path, out_path], capture_output=True, timeout=30)
        print(f"[Noctua] Saved {lib_name} to {out_path}")
        return out_path

    except Exception as e:
        print(f"[Noctua] Error pulling {lib_name}: {e}")
        return None


def main():
    parser = argparse.ArgumentParser(
        description="Noctua-c Frida Runtime Tracer Generator"
    )
    parser.add_argument("action", choices=["generate", "attach", "android", "pull"],
                        help="Action to perform")
    parser.add_argument("target", nargs="?", default="com.stellarforge.game",
                        help="Process name (attach) or package (android/pull)")
    parser.add_argument("--lib", default="libil2cpp.so",
                        help="Library name for pull action")

    args = parser.parse_args()

    if args.action == "generate":
        script = generate_script(args.target)
        print(script)

    elif args.action == "attach":
        attach_local(args.target)

    elif args.action == "android":
        attach_android(args.target)

    elif args.action == "pull":
        dump_so_from_device(args.target, args.lib)

    else:
        print("[Noctua] Unknown action")


if __name__ == "__main__":
    main()
